name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: changelog-increment.md
          push: false  # we can't push because our main branch is protected
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Cleanup created tag
        # commitzen ALWAYS creates a tag, but we don't want this behavior
        # Ref https://github.com/commitizen-tools/commitizen/issues/612
        run: |
          chown -R $(whoami) .git
          git tag -d ${{ steps.cz.outputs.version }}
          git add changelog-increment.md
          git commit --amend
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "[auto] Bump Version + Changelog"
          body: Update version and changelog
          branch: bump-version
          base: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
  release:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: "poetry.lock"
      - name: Install dependencies
        run: |
          pip install -U poetry
          poetry install --only=commit-lint --no-root
      - name: Get version
        run: |
          echo "VERSION_NUMBER=$(poetry run cz version -p)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "changelog-increment.md"
          tag_name: ${{ env.VERSION_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
