name: PR validation

on: [pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check if commits messages are following conventional commits standard
        uses: aevea/commitsar@v0.20.1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: "poetry.lock"
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: |
          poetry run flakeheaven lint
